### ISSUE TITLE
Support Azure DevOps menu link definition

### ISSUE THREAD

**Issue by SebastianSchuetze** [dlyz/md-link-checker#4]
Azure DevOps Markdown supports a tag to generate a menu:
```
[[_TOC_]]
```

![image](https://github.com/dlyz/md-link-checker/assets/7256168/b0627fb8-cbb8-48d2-92ec-28523cc70ee3)

It would be good if this could be ignored or an option to ignore these kind of things.

**Comment by SebastianSchuetze** [comment]
@dlyz Same for block extensions `:::`. They are also not supported:

![image](https://github.com/dlyz/md-link-checker/assets/7256168/03d819e8-7bfc-4baa-81c6-8599fd7aced2)

If you give me a hint on how to implement it fast. I might be able to help.

**Comment by dlyz** [comment]
Yeah, the extension doesn't support these markdown extensions. The thing is I kind of lost the motivation to evolve it mainly because shortly after its creation VSCode begin to support [link validation out of the box](https://code.visualstudio.com/docs/languages/markdown#_link-validation).

Are there any scenarios you interested in that are not supported in VSCode and supported in my extension?
The only major difference is that my extension supports external link validation and the embedded one supports only local, but there are other extensions that supports external link validation like [blackmist.LinkCheckMD](https://marketplace.visualstudio.com/items?itemName=blackmist.LinkCheckMD).

One of the problem is that my implementation is quite complex because of local link validation (and tracking of current changes in opened documents), and in order to support only external link validation it could be significantly simplified. But again, I don't see a niche for this extension anymore.

**Comment by SebastianSchuetze** [comment]
I didn't even know that this was possible in VSCode natively. I guess I had it deactivated. I will check again. If this is sufficient e Pugh then I guess my request would not be needed anymore.

**Comment by dlyz** [comment]
>  I guess I had it deactivated.

I guess it is disabled by default.

Anyway, I had some unfinished work locally, so i decided to do a little polishing and publish it. As a result, `[[_TOC_]]` is excluded from validation in 0.4.0.

As of `:::`, looks like it's Azure DevOps unique markdown extension, for example github supports mermaid diagrams in basic code blocks. It is required to patch grammar in [markdown.textmate.json](../blob/main/assets/markdown.textmate.json) in order to ignore this blocks like code blocks.

I also added information about vscode embedded markdown link validation to the readme file.
